import { Request, Response } from "express";
import mongoose from "mongoose";
import { AuthRequest } from "../middleware/auth";
import Booking from "../models/Booking";
import Fee from "../models/Fee";
import Room from "../models/Room";
import Student from "../models/Student";
import User from "../models/User";
import { logAdminAction } from "./adminLogController";
import { createNotification } from "./notificationController";

const APPROVAL_STATUSES = [
  "Pending",
  "Approved",
  "Rejected",
  "Inactive",
] as const;

const computeFeeStatus = (statuses: string[]) => {
  if (statuses.includes("Overdue")) return "Overdue";
  if (statuses.includes("Pending") || statuses.includes("Partial"))
    return "Pending";
  if (statuses.includes("Paid")) return "Paid";
  return "Pending";
};

const normalizeFeeStatus = (value: unknown): "Paid" | "Pending" | "Overdue" => {
  const status = String(value || "").trim().toLowerCase();
  if (status === "paid") return "Paid";
  if (status === "overdue") return "Overdue";
  return "Pending";
};

const buildDefaultSemester = (date = new Date()) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;

const buildDefaultDueDate = (date = new Date()) => {
  const dueDate = new Date(date);
  dueDate.setDate(dueDate.getDate() + 30);
  return dueDate;
};

const releaseRoomFromStudent = async (params: {
  roomNumber?: string;
  studentRoomKey: string;
}) => {
  const roomNumber = String(params.roomNumber || "").trim();
  if (!roomNumber) return;

  const roomDoc = await Room.findOne({ roomNumber });
  if (!roomDoc) return;

  roomDoc.students = (roomDoc.students || []).filter(
    (entry: string) => entry !== params.studentRoomKey,
  );
  roomDoc.occupied = Math.max(0, Number(roomDoc.occupied || 0) - 1);

  if (roomDoc.status !== "Maintenance") {
    roomDoc.status = "Available";
  }

  await roomDoc.save();
};

const syncStudentFeeRecord = async (params: {
  studentId: string;
  studentName: string;
  email: string;
  roomNumber?: string;
  feeStatus?: "Paid" | "Pending" | "Overdue";
}) => {
  const { studentId, studentName, email, roomNumber, feeStatus } = params;
  if (!String(studentId || "").trim()) return;
  const now = new Date();
  const existingFee = await Fee.findOne({
    studentId,
    autoGenerated: true,
  }).sort({ createdAt: -1 });

  const roomNo = String(roomNumber || "").trim();
  const roomDoc = roomNo ? await Room.findOne({ roomNumber: roomNo }) : null;
  const amount = Math.max(
    4000,
    Number(existingFee?.amount || roomDoc?.price || 0) || 4000,
  );

  const dueDate = existingFee?.dueDate || buildDefaultDueDate(now);
  const isOverdue = dueDate.getTime() < Date.now();
  const effectiveStatus: "Paid" | "Pending" | "Overdue" | "Partial" =
    feeStatus === "Paid"
      ? "Paid"
      : feeStatus === "Pending"
        ? isOverdue
          ? "Overdue"
          : "Pending"
        : feeStatus === "Overdue"
          ? "Overdue"
          : existingFee?.status === "Paid" || existingFee?.status === "Partial"
            ? existingFee.status
            : isOverdue
              ? "Overdue"
              : "Pending";

  const updatePayload: Record<string, any> = {
    studentName,
    studentId,
    email,
    roomNumber: roomNo || "Unassigned",
    room: roomNo || "Unassigned",
    floor: String(roomDoc?.floor || "Not Assigned"),
    feeType: "Monthly Hostel Fee",
    amount,
    dueDate,
    status: effectiveStatus,
    paymentStatus: effectiveStatus,
    semester: existingFee?.semester || buildDefaultSemester(now),
    autoGenerated: true,
  };

  if (effectiveStatus === "Paid") {
    updatePayload.paidAmount = amount;
    updatePayload.remainingAmount = 0;
    updatePayload.paidDate = existingFee?.paidDate || now;
    updatePayload.paymentDate = existingFee?.paymentDate || now;
    updatePayload.paymentMethod = existingFee?.paymentMethod || "Cash";
    updatePayload.transactionId =
      existingFee?.transactionId || `MANUAL-${studentId}-${now.getTime()}`;
  } else if (effectiveStatus === "Partial") {
    updatePayload.paidAmount = Number(existingFee?.paidAmount || 0);
    updatePayload.remainingAmount = Math.max(
      0,
      Number(existingFee?.remainingAmount ?? amount),
    );
    updatePayload.paidDate = existingFee?.paidDate;
    updatePayload.paymentDate = existingFee?.paymentDate;
    updatePayload.paymentMethod = existingFee?.paymentMethod;
    updatePayload.transactionId = existingFee?.transactionId;
  } else {
    updatePayload.paidAmount = 0;
    updatePayload.remainingAmount = amount;
  }

  const setPayload: Record<string, any> = { ...updatePayload };
  const unsetPayload: Record<string, string> = {};
  if (effectiveStatus !== "Paid" && effectiveStatus !== "Partial") {
    unsetPayload.paymentMethod = "";
    unsetPayload.transactionId = "";
    unsetPayload.paidDate = "";
    unsetPayload.paymentDate = "";
  }

  await Fee.findOneAndUpdate(
    { studentId, autoGenerated: true },
    {
      $set: setPayload,
      ...(Object.keys(unsetPayload).length ? { $unset: unsetPayload } : {}),
    },
    {
      upsert: true,
      new: true,
      setDefaultsOnInsert: true,
    },
  );
};

const mapUserToStudentView = (
  user: any,
  booking: any,
  feeStatuses: string[],
  studentFeeStatus?: string,
) => {
  const derivedStatus =
    !user.isActive &&
    (!user.approvalStatus || user.approvalStatus === "Approved")
      ? "Inactive"
      : user.approvalStatus || "Pending";

  return {
    _id: user._id,
    name: user.name,
    email: user.email,
    phone: user.phone || "-",
    studentId:
      user.studentId || `USR-${String(user._id).slice(-6).toUpperCase()}`,
    university: user.university || "-",
    gender: user.gender || "-",
    address: user.address || "-",
    emergencyContact: user.emergencyContact || "-",
    roomNumber:
      derivedStatus === "Inactive" ? "" : booking?.roomNumber || user.room || "",
    floor: booking?.selectedFloor || "Not Assigned",
    bookingStatus: booking?.status || "Not Booked",
    status: derivedStatus,
    isActive: user.isActive,
    fees: feeStatuses.length
      ? computeFeeStatus(feeStatuses)
      : normalizeFeeStatus(studentFeeStatus),
    createdAt: user.createdAt,
    updatedAt: user.updatedAt,
  };
};

const buildQueryFromFilters = (req: Request) => {
  const q = String(req.query.search || req.query.q || "").trim();
  const status = String(req.query.status || "").trim();

  const query: Record<string, any> = { role: "student" };

  if (q) {
    query.$or = [
      { name: { $regex: q, $options: "i" } },
      { studentId: { $regex: q, $options: "i" } },
      { email: { $regex: q, $options: "i" } },
    ];
  }

  if (APPROVAL_STATUSES.includes(status as any)) {
    query.approvalStatus = status;
  }

  return query;
};

const getStudentsWithRelations = async (req: Request) => {
  const query = buildQueryFromFilters(req);
  const floor = String(req.query.floor || "").trim();
  const roomNumber = String(req.query.roomNumber || "").trim();

  const students = await User.find(query).sort({ createdAt: -1 });
  const userIds = students.map((student) => student._id);
  const studentIds = students
    .map((student) => student.studentId)
    .filter((id): id is string => Boolean(id));

  const [bookings, fees, studentDocs] = await Promise.all([
    Booking.find({ userId: { $in: userIds }, status: "Confirmed" }).sort({
      createdAt: -1,
    }),
    Fee.find({ studentId: { $in: studentIds } }).select("studentId status"),
    Student.find({ studentId: { $in: studentIds } }).select("studentId fees"),
  ]);

  const bookingMap = new Map<string, any>();
  for (const booking of bookings) {
    const key = String(booking.userId);
    if (!bookingMap.has(key)) bookingMap.set(key, booking);
  }

  const feesMap = new Map<string, string[]>();
  for (const fee of fees) {
    const key = String(fee.studentId || "");
    const existing = feesMap.get(key) || [];
    existing.push(fee.status);
    feesMap.set(key, existing);
  }

  const studentFeesMap = new Map<string, string>();
  for (const student of studentDocs) {
    const key = String((student as any).studentId || "");
    if (key) {
      studentFeesMap.set(key, String((student as any).fees || "Pending"));
    }
  }

  let data = students.map((student) => {
    const booking = bookingMap.get(String(student._id));
    const studentId = String(student.studentId || "");
    const feeStatuses = feesMap.get(studentId) || [];
    const studentFeeStatus = studentFeesMap.get(studentId);
    return mapUserToStudentView(student, booking, feeStatuses, studentFeeStatus);
  });

  if (floor)
    data = data.filter((item) =>
      item.floor.toLowerCase().includes(floor.toLowerCase()),
    );
  if (roomNumber)
    data = data.filter((item) =>
      item.roomNumber.toLowerCase().includes(roomNumber.toLowerCase()),
    );

  return data;
};

const findStudentUserByIdentifier = async (identifier: string) => {
  const trimmedIdentifier = String(identifier || "").trim();
  if (!trimmedIdentifier) return null;

  const normalizedEmail = trimmedIdentifier.toLowerCase();
  const objectIdCandidate = mongoose.Types.ObjectId.isValid(trimmedIdentifier)
    ? new mongoose.Types.ObjectId(trimmedIdentifier)
    : null;

  // Use raw collection query first to support datasets that stored _id as string.
  const rawUser = await User.collection.findOne({
    role: "student",
    $or: [
      { _id: trimmedIdentifier as any },
      ...(objectIdCandidate ? [{ _id: objectIdCandidate }] : []),
      { studentId: trimmedIdentifier },
      { email: normalizedEmail },
    ],
  });
  if (rawUser) {
    return {
      student: rawUser as Record<string, any>,
      filter: { _id: rawUser._id },
    };
  }

  // 1) Try direct User _id lookup first.
  let studentUser = await User.findOne({
    _id: trimmedIdentifier,
    role: "student",
  });
  if (studentUser) {
    return {
      student: studentUser.toObject(),
      filter: { _id: studentUser._id },
    };
  }

  // 2) Try matching User by studentId/email.
  studentUser = await User.findOne({
    role: "student",
    $or: [
      { studentId: trimmedIdentifier },
      { email: trimmedIdentifier.toLowerCase() },
    ],
  });
  if (studentUser) {
    return {
      student: studentUser.toObject(),
      filter: { _id: studentUser._id },
    };
  }

  // 3) If an id from Student collection was passed, map it back to User via studentId/email.
  if (mongoose.Types.ObjectId.isValid(trimmedIdentifier)) {
    const studentDoc =
      await Student.findById(trimmedIdentifier).select("studentId email");
    if (studentDoc) {
      const linkedUser = await User.findOne({
        role: "student",
        $or: [
          ...(studentDoc.studentId
            ? [{ studentId: studentDoc.studentId }]
            : []),
          ...(studentDoc.email
            ? [{ email: String(studentDoc.email).toLowerCase() }]
            : []),
        ],
      });
      if (linkedUser) {
        return {
          student: linkedUser.toObject(),
          filter: { _id: linkedUser._id },
        };
      }
    }
  }

  return null;
};

const getApprovalStatus = (
  value: unknown,
): "Pending" | "Approved" | "Rejected" | "Inactive" => {
  const status = String(value || "").trim();
  if (status === "Approved" || status === "Rejected" || status === "Inactive") {
    return status;
  }
  return "Pending";
};

export const getAllStudents = async (req: Request, res: Response) => {
  try {
    const data = await getStudentsWithRelations(req);
    res.json({ success: true, count: data.length, data });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error fetching students",
      error: error.message,
    });
  }
};

export const getStudentById = async (req: Request, res: Response) => {
  try {
    const rawId = req.params.id;
    const id = Array.isArray(rawId) ? rawId[0] : rawId;
    if (!id || !mongoose.Types.ObjectId.isValid(id)) {
      return res
        .status(400)
        .json({ success: false, message: "Invalid student id" });
    }
    const student = await User.findOne({ _id: id, role: "student" });
    if (!student) {
      return res
        .status(404)
        .json({ success: false, message: "Student not found" });
    }

    const [booking, fees] = await Promise.all([
      Booking.findOne({ userId: student._id, status: "Confirmed" }).sort({
        createdAt: -1,
      }),
      Fee.find({ studentId: student.studentId || "" }).select("status"),
    ]);

    return res.json({
      success: true,
      data: mapUserToStudentView(
        student,
        booking,
        fees.map((fee) => fee.status),
      ),
    });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error fetching student",
      error: error.message,
    });
  }
};

export const createStudent = async (req: AuthRequest, res: Response) => {
  try {
    const {
      name,
      email,
      password,
      confirmPassword,
      phone,
      studentId,
      university,
      gender,
      address,
      emergencyContact,
      course,
      roomNumber,
      status,
      feeStatus,
    } = req.body;

    if (password !== confirmPassword) {
      return res.status(400).json({
        success: false,
        message: "Passwords do not match",
      });
    }

    const normalizedEmail = String(email || "")
      .toLowerCase()
      .trim();
    const normalizedStudentId = String(studentId || "")
      .toUpperCase()
      .trim();

    const existing = await User.findOne({
      $or: [{ email: normalizedEmail }, { studentId: normalizedStudentId }],
    });
    if (existing) {
      return res.status(400).json({
        success: false,
        message: "Student with same email or student ID already exists",
      });
    }

    const approvalStatus = APPROVAL_STATUSES.includes(status as any)
      ? status
      : "Approved";

    const normalizedFeeStatus = normalizeFeeStatus(feeStatus);

    const student = await User.create({
      name,
      email: normalizedEmail,
      password,
      role: "student",
      phone: String(phone || "").trim(),
      studentId: normalizedStudentId,
      university,
      gender,
      address,
      emergencyContact,
      course,
      room: roomNumber || "",
      approvalStatus,
      approvedAt: approvalStatus === "Approved" ? new Date() : undefined,
      rejectedAt: approvalStatus === "Rejected" ? new Date() : undefined,
      isActive: approvalStatus === "Approved" || approvalStatus === "Pending",
    });

    await Student.findOneAndUpdate(
      {
        $or: [
          { studentId: normalizedStudentId },
          { email: normalizedEmail },
        ],
      },
      {
        $set: {
          studentId: normalizedStudentId,
          name,
          email: normalizedEmail,
          phone: String(phone || "").trim(),
          course: course || "Computer Science",
          roomNumber: roomNumber || "",
          room: roomNumber || "Unassigned",
          status: approvalStatus === "Approved" ? "Active" : "Inactive",
          fees: normalizedFeeStatus,
          joinDate: new Date(),
          emergencyContact: {
            name: "Guardian",
            phone: String(emergencyContact || "").trim(),
            relationship: "Parent",
          },
        },
      },
      {
        upsert: true,
        setDefaultsOnInsert: true,
      },
    );

    await syncStudentFeeRecord({
      studentId: normalizedStudentId,
      studentName: name,
      email: normalizedEmail,
      roomNumber: roomNumber || "",
      feeStatus: normalizedFeeStatus,
    });

    if (approvalStatus === "Approved") {
      await createNotification(
        "Registration Approved",
        "Your hostel account has been approved. You can now log in to the student dashboard.",
        "student",
        {
          source: "Student Management",
          recipientUserId: String(student._id),
          priority: "success",
        },
      );
    }

    if (approvalStatus === "Inactive") {
      await createNotification(
        "Account Inactivated",
        "Your hostel account has been set to inactive by administration.",
        "student",
        {
          source: "Student Management",
          recipientUserId: String(student._id),
          priority: "important",
        },
      );
    }

    await createNotification(
      "New Student Added",
      `Student added: ${student.name} (${student.studentId})`,
      "student",
      { source: "Student Management", recipientType: "all_admins" },
    );

    if (req.user) {
      await logAdminAction(
        req.user.email,
        String(req.user.id),
        "Added a student",
        "student",
        String(student._id),
        student.name,
      );
    }

    return res
      .status(201)
      .json({ success: true, message: "Student created successfully" });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error creating student",
      error: error.message,
    });
  }
};

export const updateStudent = async (req: AuthRequest, res: Response) => {
  try {
    const allowedFields = ["roomNumber", "status", "feeStatus"];
    const providedFields = Object.keys(req.body || {});
    const disallowedFields = providedFields.filter(
      (field) => !allowedFields.includes(field),
    );

    if (disallowedFields.length > 0) {
      return res.status(400).json({
        success: false,
        message: `Only roomNumber, status, and feeStatus can be updated by admin. Disallowed fields: ${disallowedFields.join(", ")}`,
      });
    }

    const { roomNumber, status, feeStatus } = req.body;
    const requestedFeeStatus =
      feeStatus === undefined ? undefined : normalizeFeeStatus(feeStatus);
    const nextRoomNumber =
      typeof roomNumber === "string" ? roomNumber.trim() : undefined;

    const student = await User.findOne({ _id: req.params.id, role: "student" });
    if (!student) {
      return res
        .status(404)
        .json({ success: false, message: "Student not found" });
    }

    const previousStatus = student.approvalStatus || "Pending";
    const previousRoom = String(student.room || "").trim();
    const studentRoomKey = student.studentId || String(student._id);

    let targetRoomDoc: any = null;
    let previousRoomDoc: any = null;

    if (roomNumber !== undefined && status !== "Inactive") {
      if (nextRoomNumber) {
        targetRoomDoc = await Room.findOne({ roomNumber: nextRoomNumber });
        if (!targetRoomDoc) {
          return res
            .status(404)
            .json({ success: false, message: "Selected room not found" });
        }

        if (targetRoomDoc.status === "Maintenance") {
          return res.status(400).json({
            success: false,
            message: "Selected room is under maintenance",
          });
        }

        const isRoomChanged = previousRoom !== nextRoomNumber;
        if (isRoomChanged && targetRoomDoc.occupied >= targetRoomDoc.capacity) {
          return res.status(409).json({
            success: false,
            message: `Room ${nextRoomNumber} is full. Please select a vacant room.`,
          });
        }
      }

      if (previousRoom && previousRoom !== nextRoomNumber) {
        previousRoomDoc = await Room.findOne({ roomNumber: previousRoom });
      }

      student.room = nextRoomNumber || "";
      student.roomNumber = nextRoomNumber || "";
    }

    const previousApprovalStatus = getApprovalStatus(student.approvalStatus);

    if (status && APPROVAL_STATUSES.includes(status)) {
      // Approval decisions must happen in Student Approval Management.
      if (status === "Pending" || status === "Rejected") {
        return res.status(400).json({
          success: false,
          message:
            "Pending/Rejected transitions are only allowed from Student Approval Management.",
        });
      }

      // Activity toggle is only valid for already approved/inactive students.
      if (!["Approved", "Inactive"].includes(previousApprovalStatus)) {
        return res.status(400).json({
          success: false,
          message: "Only approved students can be activated or inactivated.",
        });
      }

      student.approvalStatus = status;
      student.approvedAt =
        status === "Approved" ? new Date() : student.approvedAt;
      student.rejectedAt = undefined;
      student.isActive = status === "Approved";

      if (status === "Inactive") {
        if (previousRoom) {
          previousRoomDoc = await Room.findOne({ roomNumber: previousRoom });
        }
        student.room = "";
        student.roomNumber = "";
        targetRoomDoc = null;
      }
    }

    await student.save();

    const didRoomChange =
      (roomNumber !== undefined && previousRoom !== (nextRoomNumber || "")) ||
      status === "Inactive";

    if (didRoomChange) {
      if (previousRoomDoc) {
        await releaseRoomFromStudent({
          roomNumber: previousRoomDoc.roomNumber,
          studentRoomKey,
        });
      }

      if (targetRoomDoc && nextRoomNumber) {
        const currentStudents = targetRoomDoc.students || [];
        if (!currentStudents.includes(studentRoomKey)) {
          targetRoomDoc.students = [...currentStudents, studentRoomKey];
        }
        targetRoomDoc.occupied = Math.min(
          targetRoomDoc.capacity,
          Number(targetRoomDoc.occupied || 0) + 1,
        );
        targetRoomDoc.status =
          Number(targetRoomDoc.occupied || 0) >= Number(targetRoomDoc.capacity || 0)
            ? "Occupied"
            : "Available";
        await targetRoomDoc.save();
      }
    }

    if (didRoomChange) {
      await createNotification(
        "Room Assignment Updated",
        status === "Inactive"
          ? `Hi ${student.name}, your room assignment has been released because your account is inactive.`
          : nextRoomNumber
          ? `Hi ${student.name}, your room assignment has been updated to ${nextRoomNumber}.`
          : `Hi ${student.name}, your room assignment has been removed by administration.`,
        "room",
        {
          source: "Room Management",
          recipientUserId: String(student._id),
          priority: "important",
        },
      );
    }

    if (status && status !== previousStatus) {
      const statusMap: Record<
        string,
        {
          title: string;
          message: string;
          priority: "normal" | "important" | "urgent" | "success";
        }
      > = {
        Approved: {
          title: "Account Approved",
          message: `Hi ${student.name}, your account status is now Approved.`,
          priority: "success",
        },
        Rejected: {
          title: "Account Rejected",
          message: `Hi ${student.name}, your account status has been set to Rejected. Contact administration for details.`,
          priority: "urgent",
        },
        Inactive: {
          title: "Account Inactive",
          message: `Hi ${student.name}, your account has been set to Inactive by administration.`,
          priority: "important",
        },
        Pending: {
          title: "Account Pending Review",
          message: `Hi ${student.name}, your account status is now Pending review.`,
          priority: "normal",
        },
      };

      const event = statusMap[status];
      if (event) {
        await createNotification(event.title, event.message, "student", {
          source: "Student Management",
          recipientUserId: String(student._id),
          priority: event.priority,
        });
      }
    }

    const studentIdForFee = String(student.studentId || "").trim();
    const existingAutoFee = studentIdForFee
      ? await Fee.findOne({ studentId: studentIdForFee, autoGenerated: true }).sort({
          createdAt: -1,
        })
      : null;
    const effectiveFeeStatus =
      requestedFeeStatus || normalizeFeeStatus(existingAutoFee?.status);

    await Student.findOneAndUpdate(
      {
        $or: [
          ...(student.studentId ? [{ studentId: student.studentId }] : []),
          ...(student.email ? [{ email: String(student.email).toLowerCase() }] : []),
        ],
      },
      {
        $set: {
          roomNumber: String(student.room || ""),
          room: String(student.room || "Unassigned"),
          status: student.approvalStatus === "Approved" ? "Active" : "Inactive",
          fees: effectiveFeeStatus,
        },
      },
      { new: true },
    );

    await syncStudentFeeRecord({
      studentId: studentIdForFee,
      studentName: student.name,
      email: String(student.email || "").trim().toLowerCase(),
      roomNumber: String(student.room || "").trim(),
      feeStatus: requestedFeeStatus,
    });

    if (req.user) {
      await logAdminAction(
        req.user.email,
        String(req.user.id),
        "Updated student details",
        "student",
        String(req.params.id),
        student.name,
      );
    }

    return res.json({ success: true, message: "Student updated successfully" });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error updating student",
      error: error.message,
    });
  }
};

export const inactivateStudent = async (req: AuthRequest, res: Response) => {
  try {
    const studentIdentifier = Array.isArray(req.params.id)
      ? req.params.id[0]
      : req.params.id;
    const resolved = await findStudentUserByIdentifier(studentIdentifier);
    if (!resolved) {
      return res
        .status(404)
        .json({ success: false, message: "Student not found" });
    }

    const { student, filter } = resolved;
    const currentStatus = getApprovalStatus(student.approvalStatus);
    if (currentStatus !== "Approved") {
      return res.status(400).json({
        success: false,
        message: "Only approved students can be inactivated.",
      });
    }

    const previousRoom = String((student as any).room || "").trim();
    const studentRoomKey =
      String((student as any).studentId || "").trim() || String(student._id);

    await releaseRoomFromStudent({
      roomNumber: previousRoom,
      studentRoomKey,
    });

    await User.collection.updateOne(filter, {
      $set: { approvalStatus: "Inactive", status: "Inactive", isActive: false },
      $unset: { approvedAt: "", room: "", roomNumber: "" },
    });

    await Student.findOneAndUpdate(
      {
        $or: [
          ...((student as any).studentId
            ? [{ studentId: (student as any).studentId }]
            : []),
          ...((student as any).email
            ? [{ email: String((student as any).email).toLowerCase() }]
            : []),
        ],
      },
      { $set: { status: "Inactive", room: "Unassigned", roomNumber: "" } },
      { new: true },
    );

    await createNotification(
      "Account Inactivated",
      `Hi ${student.name}, your account has been marked inactive by administration. Please contact hostel administration for support.`,
      "student",
      {
        source: "Student Management",
        recipientUserId: String(student._id),
        priority: "important",
      },
    );

    if (req.user) {
      await logAdminAction(
        req.user.email,
        String(req.user.id),
        "Inactivated a student",
        "student",
        String(req.params.id),
        student.name,
      );
    }

    return res.json({
      success: true,
      message: "Student inactivated successfully",
    });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error inactivating student",
      error: error.message,
    });
  }
};

export const activateStudent = async (req: AuthRequest, res: Response) => {
  try {
    const studentIdentifier = Array.isArray(req.params.id)
      ? req.params.id[0]
      : req.params.id;
    const resolved = await findStudentUserByIdentifier(studentIdentifier);
    if (!resolved) {
      return res
        .status(404)
        .json({ success: false, message: "Student not found" });
    }

    const { student, filter } = resolved;
    const currentStatus = getApprovalStatus(student.approvalStatus);
    if (currentStatus !== "Inactive") {
      return res.status(400).json({
        success: false,
        message: "Only inactive approved students can be activated.",
      });
    }

    await User.collection.updateOne(filter, {
      $set: {
        approvalStatus: "Approved",
        status: "Approved",
        approvedAt: new Date(),
        isActive: true,
        room: "",
        roomNumber: "",
      },
      $unset: { rejectedAt: "" },
    });

    await Student.findOneAndUpdate(
      {
        $or: [
          ...(student.studentId ? [{ studentId: student.studentId }] : []),
          { email: student.email },
        ],
      },
      { status: "Active", room: "Unassigned", roomNumber: "" },
    );

    await createNotification(
      "Account Activated",
      `Hi ${student.name}, your account has been activated. You can now access hostel services.`,
      "student",
      {
        source: "Student Management",
        recipientUserId: String(student._id),
        priority: "success",
      },
    );

    if (req.user) {
      await logAdminAction(
        req.user.email,
        String(req.user.id),
        "Activated a student",
        "student",
        String(req.params.id),
        student.name,
      );
    }

    return res.json({
      success: true,
      message: "Student activated successfully",
    });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error activating student",
      error: error.message,
    });
  }
};

export const searchStudents = async (req: Request, res: Response) => {
  try {
    req.query.search = req.params.query;
    const data = await getStudentsWithRelations(req);
    return res.json({ success: true, count: data.length, data });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error searching students",
      error: error.message,
    });
  }
};

export const getPendingStudents = async (req: Request, res: Response) => {
  try {
    req.query.status = "Pending";
    const data = await getStudentsWithRelations(req);
    return res.json({ success: true, count: data.length, data });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error fetching pending students",
      error: error.message,
    });
  }
};

export const approveStudent = async (req: AuthRequest, res: Response) => {
  try {
    const studentIdentifier = Array.isArray(req.params.id)
      ? req.params.id[0]
      : req.params.id;
    const resolved = await findStudentUserByIdentifier(studentIdentifier);
    if (!resolved) {
      return res
        .status(404)
        .json({ success: false, message: "Student not found" });
    }

    const { student, filter } = resolved;
    const currentStatus = getApprovalStatus(student.approvalStatus);
    if (currentStatus !== "Pending") {
      return res.status(400).json({
        success: false,
        message: "Only pending students can be approved.",
      });
    }

    await User.collection.updateOne(filter, {
      $set: {
        approvalStatus: "Approved",
        status: "Approved",
        approvedAt: new Date(),
        isActive: true,
      },
      $unset: { rejectedAt: "" },
    });

    await Student.findOneAndUpdate(
      {
        $or: [
          ...(student.studentId ? [{ studentId: student.studentId }] : []),
          ...(student.email ? [{ email: student.email }] : []),
        ],
      },
      { status: "Active" },
    );

    await createNotification(
      "Registration Approved",
      `Hi ${student.name}, your account has been approved. You can now access the student dashboard.`,
      "student",
      {
        source: "Student Management",
        recipientUserId: String(student._id),
        priority: "success",
      },
    );

    if (req.user) {
      await logAdminAction(
        req.user.email,
        String(req.user.id),
        "Approved student registration",
        "student",
        String(student._id),
        student.name,
      );
    }

    return res.json({
      success: true,
      message: "Student approved successfully",
    });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error approving student",
      error: error.message,
    });
  }
};

export const rejectStudent = async (req: AuthRequest, res: Response) => {
  try {
    const studentIdentifier = Array.isArray(req.params.id)
      ? req.params.id[0]
      : req.params.id;
    const resolved = await findStudentUserByIdentifier(studentIdentifier);
    if (!resolved) {
      return res
        .status(404)
        .json({ success: false, message: "Student not found" });
    }

    const { student, filter } = resolved;
    const currentStatus = getApprovalStatus(student.approvalStatus);
    if (currentStatus !== "Pending") {
      return res.status(400).json({
        success: false,
        message: "Only pending students can be rejected.",
      });
    }

    await User.collection.updateOne(filter, {
      $set: {
        approvalStatus: "Rejected",
        status: "Rejected",
        rejectedAt: new Date(),
        isActive: false,
      },
      $unset: { approvedAt: "" },
    });

    await Student.findOneAndUpdate(
      {
        $or: [
          ...(student.studentId ? [{ studentId: student.studentId }] : []),
          ...(student.email ? [{ email: student.email }] : []),
        ],
      },
      { status: "Inactive" },
    );

    await createNotification(
      "Registration Rejected",
      `Hi ${student.name}, your account registration was rejected. Please contact hostel administration for details.`,
      "student",
      {
        source: "Student Management",
        recipientUserId: String(student._id),
        priority: "urgent",
      },
    );

    if (req.user) {
      await logAdminAction(
        req.user.email,
        String(req.user.id),
        "Rejected student registration",
        "student",
        String(student._id),
        student.name,
      );
    }

    return res.json({
      success: true,
      message: "Student rejected successfully",
    });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: "Error rejecting student",
      error: error.message,
    });
  }
};
