import mongoose, { Document, Schema } from 'mongoose';

export interface IFee extends Document {
  studentName: string;
  studentId: string;
  email?: string;
  roomNumber: string;
  room: string;
  floor: string;
  feeType: 'Monthly' | 'Hostel' | 'Fine' | 'Other' | 'Monthly Hostel Fee' | 'Maintenance Fee' | 'Mess Fee' | 'Library Fee';
  amount: number;
  dueDate: Date;
  status: 'Paid' | 'Pending' | 'Overdue' | 'Partial';
  paymentStatus: 'Paid' | 'Pending' | 'Overdue' | 'Partial';
  paymentDate?: Date;
  paidDate?: Date;
  paymentMethod?: string;
  transactionId?: string;
  semester: string;
  academicYear?: string;
  paidAmount?: number;
  remainingAmount?: number;
  notes?: string;
  paymentNotes?: string;
  autoGenerated?: boolean;
  bookingId?: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const FeeSchema: Schema = new Schema({
  studentName: {
    type: String,
    required: true,
    trim: true
  },
  studentId: {
    type: String,
    required: true,
    ref: 'Student'
  },
  email: {
    type: String,
    trim: true,
    lowercase: true,
  },
  room: {
    type: String,
    required: true
  },
  roomNumber: {
    type: String,
    required: true,
    trim: true
  },
  floor: {
    type: String,
    required: true,
    trim: true,
    default: ''
  },
  feeType: {
    type: String,
    required: true,
    enum: ['Monthly', 'Hostel', 'Fine', 'Other', 'Monthly Hostel Fee', 'Maintenance Fee', 'Mess Fee', 'Library Fee']
  },
  amount: {
    type: Number,
    required: true,
    min: [1, 'Amount must be greater than 0']
  },
  dueDate: {
    type: Date,
    required: true
  },
  status: {
    type: String,
    enum: ['Paid', 'Pending', 'Overdue', 'Partial'],
    default: 'Pending'
  },
  paymentStatus: {
    type: String,
    enum: ['Paid', 'Pending', 'Overdue', 'Partial'],
    default: 'Pending'
  },
  paidDate: {
    type: Date
  },
  paymentDate: {
    type: Date
  },
  paymentMethod: {
    type: String,
    enum: ['Online Transfer', 'Cash', 'Credit Card', 'Bank Transfer', 'Debit Card']
  },
  transactionId: {
    type: String,
    trim: true,
    default: undefined
  },
  semester: {
    type: String,
    required: true
  },
  academicYear: {
    type: String,
    trim: true
  },
  paidAmount: {
    type: Number,
    min: 0,
    default: 0
  },
  remainingAmount: {
    type: Number,
    min: 0
  },
  notes: {
    type: String,
    trim: true
  },
  paymentNotes: {
    type: String,
    trim: true
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  bookingId: {
    type: Schema.Types.ObjectId,
    ref: 'Booking'
  }
}, {
  timestamps: true
});

FeeSchema.index({ studentId: 1 });
// Unique only when transactionId exists (and is not an empty string).
FeeSchema.index(
  { transactionId: 1 },
  {
    unique: true,
    sparse: true,
  }
);

export default mongoose.model<IFee>('Fee', FeeSchema);
